[package]
name = "dummy-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["full"] }
tower = "0.5.2"
http-body-util = "0.1.3"
clap = { version = "4.5.38", features = ["derive"] }
uuid = { version = "1.18.1", features = ['v4'] }
